name: Deploy React App to HostNeverDie

on:
  push:
    branches:
      - main  # รันเมื่อ Push ไปที่ branch main

jobs:
  deploy-client:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies & Build React App
        run: |
          npm install
          npm run build  # สร้างไฟล์ production

      - name: Debug Build Output  # ตรวจสอบว่าไฟล์ถูกสร้างหรือไม่
        run: ls -lah dist/  # ต้องเป็น `build/` ไม่ใช่ `dist/`

      - name: Deploy Client via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 2121  # พอร์ตของโฮสต์
          protocol: ftps  # ใช้ `ftps` ถ้าเซิร์ฟเวอร์รองรับ FTPS
          local-dir: dist/  # React สร้างไฟล์ที่ `build/`
          server-dir: public_html/  # ปรับให้ตรงกับโฮสต์ของคุณ
